### ISSUE TITLE
Make opening all links in new tabs optional

### ISSUE THREAD

**Issue by khaledh** [bachmitre/hacker-news-highlighter#4]
While opening stories in new tabs is fine, I feel that it's an overkill to open _all_ links in new tabs, including comments, flag, and the "more" link at the bottom.

It's also not what the extension advertises: just highlight new articles.

**Comment by bachmitre** [comment]
You are right. The reason it opens a new tab for everything is that I wanted a reload of the front page to un-highlight articles that were previously highlighted, and only show new articles (reload meaning: i read all the headlines, now show me what is new since last reload) .. 
If you had a front-page with highlighted new articles, and would open any comments in the same window, then hit the "back" button to go back to the front-page, this is also considered a reload, and you would loose all the previously highlighted articles ...
There might be other / better ways to deal with this..

**Comment by khaledh** [comment]
I see. Thanks for explaining, this makes sense.

I think this is a hard problem to solve: how do you consider stories _seen_? Is it after a page reload, or after some time passes, or when the user visits/clicks the story? Different users may have different expectations.

I'll leave it up to you to consider what the best approach is. Feel free to close this issue if it's something you consider not feasible (at least for the time being).

**Comment by bachmitre** [comment]
Yes, this is very specific to how I read HN:
I have a HN tab open that I come back to multiple times a day. Before I created this extension I would reload the HN page and go through each headline to see what is new. I had to read each headline (even the ones I already read) to find the new articles. 
Now I can reload and directly see which articles are new since my last reload.
